excercise part I
kareraolivier/TheGym-nine-react-exercise pull request #1
Opened 2023-09-26 15:38 UTC by kareraolivier

# PR for Exercises

### This PR contains the collection of all nine exercises and in the repo, they are arranged each on it's own folder.

## Here we have screenshots of every exercise

### Exercise I
### Exercise I

2023-10-05 13:01 UTC, divinecharlotte requested changes
hi @kareraolivier check the comment below 👇

2023-10-05 13:01 UTC, divinecharlotte commented on src/components/fetchdata/FetchData.jsx
> +// import Loading from "../loading/Loading";
- [ ] kindly consider removing all the commented codes as they make your code base look kinda messy if you are not using some parts of codes its better to delete them completely

2023-10-05 14:46 UTC, kareraolivier commented on src/components/fetchdata/FetchData.jsx
> +// import Loading from "../loading/Loading";
I removed them

2023-10-13 11:52 UTC, Yvad60 requested changes
Good work @kareraolivier on the changes. I have left some suggestions on how to improve the current codebase

One main thing to work on is variable and file naming conventions. This includes using the right casing and making names descriptive.
Also when you rework on these code reviews don't only changes the parts i have highlighted instead check the whole codebase and change wherever applicable 

cheers

2023-10-13 11:52 UTC, Yvad60 commented on src/components/stateandprops/StateandProps.jsx
> +const StateandProps = () => {
React components should be named in Pascal case. Better to rename this to `StateAndProps`

2023-10-13 11:52 UTC, Yvad60 commented on src/components/stateandprops/StateandProps.jsx
> +  };
There is a typo in the name of this function. Did you mean `handleClick`?

2023-10-13 11:52 UTC, Yvad60 commented on src/components/stateandprops/ButtonComp.jsx
> +const ButtonComp = ({ hundleClick }) => {
You don't have to mention the type of the variable in its name. Naming the function in Pascal case should tell that it's a component, you don't need to explicitly mention that it is a `comp`(component). In this case you can just name it `Button`

2023-10-13 11:52 UTC, Yvad60 commented on src/components/stateandprops/ButtonComp.jsx
> +        onClick={hundleClick}
Here also it should be `handleClick`

2023-10-13 11:52 UTC, Yvad60 commented on src/components/mappingdata/DataList.jsx
> +const DataList = ({ DataLists }) => {
Props and their properties are treated as normal variables therefore they should be named in camel case likt `dataLists`

2023-10-13 11:52 UTC, Yvad60 commented on src/components/mappingdata/DataList.jsx
> +    </div>
For correct HTML semantics. list items should be direct children of an unordered list `ul` or ordered list `ul` not a `div`

2023-10-13 11:52 UTC, Yvad60 commented on src/components/mappingdata/MappingData.jsx
> +import CompanyData from "../data/companyLog.json";
These should also be named in camel case since are normal variables

General comment: You may also check other places (I noticed a few more places) where variables are named in the wrong case and update it too

2023-10-13 11:52 UTC, Yvad60 commented on src/components/customComponent/CustomComponent.jsx
> +    </div>
I think you may not need an extra wrapper `div` since  the content is already wrapped inside another `div` anyway

2023-10-13 11:52 UTC, Yvad60 commented on src/components/buildform/LoginForm.jsx
> +  };
Can you prevent it from alerting when the input empty 😃 ?

2023-10-13 11:52 UTC, Yvad60 commented on src/components/fetchdata/FetchData.jsx
> +    console.log("karera", data);
Remember to remove the console logs when you are done testing

2023-10-13 11:52 UTC, Yvad60 commented on src/components/fetchdata/FetchData.jsx
> +  const [user, setUser] = useState([]);
I am assuming that this will be an array so it would be better to name it plural :`users`

2023-10-13 11:52 UTC, Yvad60 commented on src/components/header/NavList.jsx
Since this file does not include any React code it does not have to be named with a `.jsx` extension. You can name it with a `.js` extension for more clarity

2023-10-13 12:31 UTC, kareraolivier commented on src/components/buildform/LoginForm.jsx
> +  };
It is fixed

2023-10-13 12:34 UTC, kareraolivier commented on src/components/customComponent/CustomComponent.jsx
> +    </div>
fixed

2023-10-13 12:41 UTC, kareraolivier commented on src/components/fetchdata/FetchData.jsx
> +  const [user, setUser] = useState([]);
fixed

2023-10-13 12:41 UTC, kareraolivier commented on src/components/fetchdata/FetchData.jsx
> +    console.log("karera", data);
fixed

2023-10-13 12:43 UTC, kareraolivier commented on src/components/header/NavList.jsx
Vite does not work with js files may be I can make them a json file.

2023-10-13 12:49 UTC, kareraolivier commented on src/components/mappingdata/DataList.jsx
> +    </div>
fixed

2023-10-13 12:50 UTC, kareraolivier commented on src/components/mappingdata/DataList.jsx
> +const DataList = ({ DataLists }) => {
fixed

2023-10-13 12:51 UTC, kareraolivier commented on src/components/mappingdata/MappingData.jsx
> +import CompanyData from "../data/companyLog.json";
fixed

2023-10-13 12:57 UTC, kareraolivier commented on src/components/stateandprops/ButtonComp.jsx
> +const ButtonComp = ({ hundleClick }) => {
fixed

2023-10-13 12:57 UTC, kareraolivier commented on src/components/stateandprops/ButtonComp.jsx
> +        onClick={hundleClick}
fixed

2023-10-13 12:58 UTC, kareraolivier commented on src/components/stateandprops/StateandProps.jsx
> +const StateandProps = () => {
fixed

2023-10-13 13:01 UTC, kareraolivier commented on src/components/stateandprops/StateandProps.jsx
> +  };
fixed

2023-10-13 13:54 UTC, Yvad60 requested changes
Good job on the changes. I have left a few more suggestions

2023-10-13 13:54 UTC, Yvad60 commented on src/components/stateandprops/StateandProps.jsx
> +const StateandProps = () => {
> React components should be named in Pascal case. Better to rename this to `StateAndProps`

Did you check this?

2023-10-13 13:54 UTC, Yvad60 commented on src/components/stateandprops/ButtonComp.jsx
When you rename the component also rename the File since React components should have the same name as their `.jsx` files

2023-10-13 13:54 UTC, Yvad60 commented on src/components/header/NavList.jsx
I think Vite should work with `.js` by default

2023-10-13 13:54 UTC, Yvad60 commented on src/components/header/NavList.json
Can you name this in camel case since it is a normal file like `navList`

2023-10-13 14:36 UTC, kareraolivier commented on src/components/header/NavList.json
done

2023-10-13 14:37 UTC, kareraolivier commented on src/components/stateandprops/ButtonComp.jsx
ok this is now fixed

2023-10-13 16:09 UTC, Yvad60 approved these changes
Good job! Looks good to me now

2023-11-01 15:03 UTC, merged